# Generated by Django 5.0.1 on 2024-02-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SectorStandards",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=255)),
                ("sector_standard", models.CharField(max_length=255, null=True)),
                ("sector_label", models.TextField()),
            ],
        ),
    ]
