# Generated by Django 5.0.1 on 2024-02-14 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stDataApp", "0003_company_raw_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_data", models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name="company",
            name="raw_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stDataApp.rawdata"
            ),
        ),
    ]
