# Generated by Django 5.0.1 on 2024-02-14 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stDataApp", "0005_alter_rawdata_raw_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="stDataApp.country",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_sector_standard",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="stDataApp.sectorstandards",
            ),
        ),
    ]
