# Generated by Django 5.0.1 on 2024-02-15 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stDataApp", "0007_excelfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="raw_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stDataApp.excelfile"
            ),
        ),
    ]
