# Generated by Django 5.0.1 on 2024-02-16 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stDataApp", "0008_alter_company_raw_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RawData",
        ),
    ]
