# Generated by Django 5.0.1 on 2024-02-18 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stDataApp", "0010_modelprove"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModelProve",
        ),
    ]
