# Generated by Django 5.0.1 on 2024-02-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stDataApp", "0011_delete_modelprove"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelProve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kodi", models.CharField(max_length=255)),
            ],
        ),
    ]
