# Generated by Django 5.0.1 on 2024-02-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stDataApp", "0012_modelprove"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelProveNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_standarti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stDataApp.sectorstandards",
                    ),
                ),
            ],
        ),
    ]
